### ISSUE TITLE
Update Model 

### ISSUE THREAD

**Issue by uniyall** [Jeet-beep/WeHealth#1]
Pls push the updated model so that the deployment can be updated with the latest commit 🙏🏼

**Comment by Jeet-beep** [comment]
Hi Prateek,

Thank you for your request to push the updated model for deployment. I
understand the urgency, but I'm currently tied up with some work that I
need to complete in the next couple of hours. Rest assured, I will
prioritize pushing the updated model as soon as I am available, and it
should be done within the next 2 hours.

I appreciate your patience, and I'll make sure to keep you updated on the
progress.

Best regards,
Jeet

**Comment by uniyall** [comment]
okay, i am closing the issue.
